version: '3'
services:
  eshiritori-api:
    environment:
      PYTHONPATH: src/
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'eshiritori-api'
    tty: true
    volumes:
      - .:/eshiritori-api/
    ports:
      - "8000:8000"