version: '3'
services:
  eshiritori-api:
    environment:
      PYTHONPATH: ./
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'eshiritori-api'
    tty: true
    volumes:
      - .:/eshiritori-api/
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ['gpu']